FROM golang:1.19-alpine

ARG DB_PASSWORD
ARG JWT_SECRET
ARG SUPER_ADMIN_EMAIL
ARG SMTP_PASSWORD
ARG MINIO_ACCESS_KEY_ID
ARG MINIO_SECRET_ACCESS_KEY

ENV DB_PASSWORD $DB_PASSWORD
ENV SMTP_PASSWORD $SMTP_PASSWORD
ENV SUPER_ADMIN_EMAIL $SUPER_ADMIN_EMAIL
ENV JWT_SECRET $JWT_SECRET
ENV MINIO_ACCESS_KEY_ID $MINIO_ACCESS_KEY_ID
ENV MINIO_SECRET_ACCESS_KEY $MINIO_SECRET_ACCESS_KEY

# Set destination for COPY
WORKDIR /app

# Download Go modules
COPY go.mod .
COPY go.sum .
RUN go mod download

COPY ./ ./

COPY /migrations/*.sql /app/migrations

# Build
RUN go build -o /cmd/server ./cmd/server/main.go

# Run
CMD [ "/cmd/server" ]