// Code generated by mockery v2.15.0. DO NOT EDIT.

package app

import mock "github.com/stretchr/testify/mock"

// MockOnShutdownFunc is an autogenerated mock type for the OnShutdownFunc type
type MockOnShutdownFunc struct {
	mock.Mock
}

// Execute provides a mock function with given fields:
func (_m *MockOnShutdownFunc) Execute() {
	_m.Called()
}

type mockConstructorTestingTNewMockOnShutdownFunc interface {
	mock.TestingT
	Cleanup(func())
}

// NewMockOnShutdownFunc creates a new instance of MockOnShutdownFunc. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockOnShutdownFunc(t mockConstructorTestingTNewMockOnShutdownFunc) *MockOnShutdownFunc {
	mock := &MockOnShutdownFunc{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
