// Code generated by mockery v2.15.0. DO NOT EDIT.

package app

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockOnStart is an autogenerated mock type for the OnStart type
type MockOnStart struct {
	mock.Mock
}

// Execute provides a mock function with given fields: _a0, _a1
func (_m *MockOnStart) Execute(_a0 context.Context, _a1 *App) ([]Listener, error) {
	ret := _m.Called(_a0, _a1)

	var r0 []Listener
	if rf, ok := ret.Get(0).(func(context.Context, *App) []Listener); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]Listener)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *App) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewMockOnStart interface {
	mock.TestingT
	Cleanup(func())
}

// NewMockOnStart creates a new instance of MockOnStart. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockOnStart(t mockConstructorTestingTNewMockOnStart) *MockOnStart {
	mock := &MockOnStart{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
