http:
  port: "8080"
  allowed_methods: "POST, GET, OPTIONS, DELETE"
  allowed_headers: "Content-Type, Authorization"

db:
  host: "localhost"
  port: "5432"
  user: "postgres"
  db_name: "postgres"
  ssl_mode: "disable"

sentry:
  dsn: "https://7ccdffeddedf43a798f350430fbb20f1@o4504101310562304.ingest.sentry.io/4504117921316864"
  enable: true

super_admin:
  name: "Федор Хлебалов"

smtp:
  host: "smtp.mail.ru"
  port: "587"
  email: "gamification-noreply@mail.ru"

auth:
  fake_auth_enabled: true
  fake_auth_headers: "Content-Type, Authorization, X-Auth-Role, X-Auth-User-ID"

s3:
  endpoint: "s3.eu-central-1.amazonaws.com"
  region: "eu-central-1"
  bucket: "gamification-api"

folders:
  users: "avatars"
  achievements: "achievements"
  events: "events"
