// Code generated by mockery v2.15.0. DO NOT EDIT.

package http

import (
	mux "github.com/gorilla/mux"
	mock "github.com/stretchr/testify/mock"
)

// MockService is an autogenerated mock type for the Service type
type MockService struct {
	mock.Mock
}

// AddRoutes provides a mock function with given fields: r
func (_m *MockService) AddRoutes(r *mux.Router) error {
	ret := _m.Called(r)

	var r0 error
	if rf, ok := ret.Get(0).(func(*mux.Router) error); ok {
		r0 = rf(r)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewMockService interface {
	mock.TestingT
	Cleanup(func())
}

// NewMockService creates a new instance of MockService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockService(t mockConstructorTestingTNewMockService) *MockService {
	mock := &MockService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
