name: Releases CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: vokhlebalov/gamification:latest
          build-args: |
            DB_PASSWORD=${{ secrets.DB_PASSWORD }}
            JWT_SECRET=${{ secrets.JWT_SECRET }}
            SMTP_PASSWORD=${{ secrets.SMTP_PASSWORD }}
            SUPER_ADMIN_EMAIL=${{ secrets.SUPER_ADMIN_EMAIL }}
            MINIO_SECRET_ACCESS_KEY=${{ secrets.MINIO_SECRET_ACCESS_KEY }}
            MINIO_ACCESS_KEY_ID=${{ secrets.MINIO_ACCESS_KEY_ID }}

  migration:
    name: migrations
    needs: [build]
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        go-version: [ 1.19.x ]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}

      - name: Install goose
        run: go install github.com/pressly/goose/v3/cmd/goose@latest
      - run: pwd
      - name: Run migrations
        run: goose postgres "user=gamification_api password=${{ secrets.DB_PASSWORD }} dbname=gamification_api host=vartose.fvds.ru port=5432 sslmode=disable" up
        working-directory: ./migrations


  deploy:
    name: deploy
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Deploy docker container webhook
        uses: joelwmale/webhook-action@master
        env:
          WEBHOOK_URL: ${{ secrets.DEPLOY_WEBHOOK_URL  }}